name       : python-gast
version    : 0.2.2
release    : 2
source     :
    - https://github.com/serge-sans-paille/gast/archive/0.2.2.tar.gz : 91f49fe8784cb8012212a430f4fa8590d8be93e1653692d184772f05a5feb6b9
license    : BSD-3-Clause
component  : programming.python
summary    : Python AST that abstracts the underlying Python version
description: |
    A generic AST to represent Python2 and Python3's Abstract Syntax Tree(AST).
build      : |
    %python3_setup
install    : |
    %python3_install
