name       : llvm-6
version    : 6.0.1
release    : 3
source     :
    - https://releases.llvm.org/6.0.1/llvm-6.0.1.src.tar.xz : b6d6c324f9c71494c0ccaf3dac1f16236d970002b42bb24a6c9e1634f7d0f4e2
    - https://releases.llvm.org/6.0.1/cfe-6.0.1.src.tar.xz : 7c243f1485bddfdfedada3cd402ff4792ea82362ff91fbdac2dae67c6026b667
    - https://releases.llvm.org/6.0.1/compiler-rt-6.0.1.src.tar.xz : f4cd1e15e7d5cb708f9931d4844524e4904867240c306b06a4287b22ac1c99b9
    - https://releases.llvm.org/6.0.1/lld-6.0.1.src.tar.xz : e706745806921cea5c45700e13ebe16d834b5e3c0b7ad83bf6da1f28b0634e11
      #- https://releases.llvm.org/6.0.1/lldb-6.0.1.src.tar.xz : 6b8573841f2f7b60ffab9715c55dceff4f2a44e5a6d590ac189d20e8e7472714
    - https://releases.llvm.org/6.0.1/clang-tools-extra-6.0.1.src.tar.xz : 0d2e3727786437574835b75135f9e36f861932a958d8547ced7e13ebdda115f1
    - https://releases.llvm.org/6.0.1/libcxx-6.0.1.src.tar.xz : 7654fbc810a03860e6f01a54c2297a0b9efb04c0b9aa0409251d9bdb3726fc67
    - https://releases.llvm.org/6.0.1/libcxxabi-6.0.1.src.tar.xz : 209f2ec244a8945c891f722e9eda7c54a5a7048401abd62c62199f3064db385f
    - https://releases.llvm.org/6.0.1/openmp-6.0.1.src.tar.xz : 66afca2b308351b180136cf899a3b22865af1a775efaf74dc8a10c96d4721c5a
homepage   : http://llvm.org/
license    :
    - NCSA
summary    :
    - Low Level Virtual Machine (Reusable compiler and toolchains)
    - ^llvm-clang-6 : Clang Compiler frontend to LLVM
    - ^llvm-clang-6-devel : Development files for building clang plugins
    - ^llvm-clang-6-32bit : 32bit libraries for clang
component  :
    - programming
    - ^llvm-clang-6 : programming
    - ^llvm-clang-6-32bit : emul32
    - ^llvm-clang-6-32bit-devel : programming.devel
debug      : no
libsplit   : no
clang      : yes
builddeps  :
    - pkgconfig32(libffi)
    - pkgconfig32(libxml-2.0)
    - pkgconfig(libedit)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
    - doxygen
    - swig
rundeps    :
    - ^llvm-clang-6 :
        - llvm-6-devel
        - python-six
    - ^llvm-clang-6-devel :
        - llvm-clang-6
    - ^llvm-clang-6-32bit-devel :
        - llvm-clang-6-32bit
        - llvm-clang-6-devel
description: |
    The LLVM package contains a collection of modular and reusable compiler and toolchain technologies. The Low Level Virtual Machine (LLVM) Core libraries provide a modern source and target-independent optimizer, along with code generation support for many popular CPUs (as well as some less common ones!). These libraries are built around a well specified code representation known as the LLVM intermediate representation ("LLVM IR").
patterns   :
    - ^llvm-clang-6-devel :
        - /usr/local/include/clang*
        - /usr/local/include/lld*
          #- /usr/local/include/lldb*
        - /usr/local/include/openmp*
        - /usr/local/lib64/libclang*.a
          #- /usr/local/lib64/liblldb*.a
    - ^llvm-clang-6-32bit :
        - /usr/local/lib32/libclang*.so*
          #- /usr/local/lib32/liblldb*.so*
        - /usr/local/lib32/lib*omp*.so
    - ^llvm-clang-6-32bit-devel :
        - /usr/local/lib32/libclang*.a
          #- /usr/local/lib32/liblldb*.a
        - /usr/local/lib32/clang
        - /usr/local/lib32/cmake/
    - ^llvm-clang-6 :
        - /usr/local/bin
        - /usr/local/libexec
        - /usr/local/lib64/clang
          #- /usr/local/lib64/liblldb*.so*
        - /usr/local/lib64/libclang*.so*
          #- /usr/local/lib64/python2.7/site-packages/lldb/
        - /usr/local/lib64/lib*omp*.so
        - /usr/local/share/man/*/*clang*
        - /usr/local/share/man/*/*scan-build*
        - /usr/local/share/llvm/cmake
        - /usr/local/share/clang
        - /usr/local/share/opt-viewer
        - /usr/local/share/scan-build
        - /usr/local/share/scan-view
    - devel :
        - /usr/local/bin/bugpoint
        - /usr/local/bin/lli*
        - /usr/local/bin/llc*
        - /usr/local/bin/llv*
        - /usr/local/bin/macho-dump
        - /usr/local/bin/opt
          #replaces   :
          #    - clang : clang
          #    - clang-devel : clang-devel
setup      : |
    # llvm patches
    %patch -p1 < $pkgfiles/0001-llvm-Let-the-linker-find-the-correct-ffi-as-cmake-br.patch
    %patch -p1 < $pkgfiles/D44391-export-LLVM_DYLIB_COMPONENTS-in-LLVMConfig.cmake.patch

    mkdir DISABLED_AREA
    mkdir -p tools
    # Set up our tools (cfe)
    tar xf $sources/cfe-${version}.src.tar.xz -C tools
    mv tools/cfe-${version}.src tools/clang

    # Set up tools (lld)
    tar xf $sources/lld-${version}.src.tar.xz -C tools
    mv tools/lld-${version}.src tools/lld

    # Set up clang-tools-extra
    tar xf $sources/clang-tools-extra-${version}.src.tar.xz -C tools/clang/tools
    mv tools/clang/tools/clang-tools-extra-${version}.src tools/clang/tools/extra

    # Now set up all of the projects (compiler-rt, libcxx, libcxxabi, openmp)
    mkdir -p projects
    for project in compiler-rt libcxx libcxxabi openmp ; do
        tar xf $sources/${project}-${version}.src.tar.xz -C projects
        mv projects/${project}-${version}.src projects/${project}
    done

    # Patch cfe for Solus specific options
    pushd tools/clang
    %patch -p1 < $pkgfiles/0001-cfe-Use-correct-Solus-multilib-paths.patch
    %patch -p1 < $pkgfiles/0002-cfe-Use-the-GNU-hash-style-for-Solus-binary-build-id.patch
    %patch -p1 < $pkgfiles/0003-cfe-Link-properly-to-multilib-xml2-library.patch
    popd

    #pushd tools/lldb
    #%patch -p1 < $pkgfiles/0001-Fix-python-path-as-python-still-in-lib-directory.patch
    #popd

    # Override compilers for this first run
    export CC=clang
    export CXX=clang++

    # Configure
    mkdir sol-stage1
    mkdir sol-stage2

    export _LLVM_TRIPLE="%HOST%"
    export _LLVM_ARCH="x86_64"
    export _LLVM_FLAGS_BOOTSTRAP="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe"
    export _LLVM_FLAGS_FINAL="-march=x86-64 -mtune=generic -gline-tables-only -O3 -fstack-protector -pipe -DNDEBUG"

    # Decontaminate environment for stage1 compilation
    export CFLAGS="$_LLVM_FLAGS_BOOTSTRAP"
    export CXXFLAGS="$_LLVM_FLAGS_BOOTSTRAP"
    unset LDFLAGS
    unset LD_AS_NEEDED

    # Before we start, disable lldb/lld
    mv tools/lld DISABLED_AREA/lld
    #mv tools/lldb DISABLED_AREA/lldb
    mv projects/libcxx DISABLED_AREA/libcxx
    mv projects/libcxxabi DISABLED_AREA/libcxxabi
    mv projects/openmp DISABLED_AREA/openmp

    # Start stage1 bootstrap
    pushd sol-stage1
    cmake .. \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_C_FLAGS_RELEASE="$CFLAGS" \
        -DCMAKE_CXX_FLAGS_RELEASE="$CXXFLAGS" \
        -DLLVM_TARGET_ARCH=$_LLVM_ARCH \
        -DLLVM_BINUTILS_INCDIR=/usr/local/include \
        -DLLVM_DEFAULT_TARGET_TRIPLE=$_LLVM_TRIPLE \
        -DLLVM_ENABLE_RTTI=OFF \
        -DLLVM_ENABLE_PIC=ON \
        -DLLVM_ENABLE_ASSERTIONS=OFF \
        -DLLVM_TARGETS_TO_BUILD="host;AMDGPU;BPF" \
        -DLLVM_ENABLE_CXX1Y=ON \
        -DLLVM_BUILD_LLVM_DYLIB=ON \
        -DLLVM_LINK_LLVM_DYLIB=ON \
        -G Ninja
    LC_ALL=en_US.utf8 ninja %JOBS% -v
    popd

    # Use our stage1 compiler
    STAGE1DIR=$(realpath ./sol-stage1/bin)
    # We need to preserve the symlink in the name during invocation
    export CC="${STAGE1DIR}/clang"
    export CXX="${STAGE1DIR}/clang++"

    # Set up stage2 final flags
    export CFLAGS="$_LLVM_FLAGS_FINAL"
    export CXXFLAGS="$_LLVM_FLAGS_FINAL"

    # For stage2 2, re-enable them
    mv DISABLED_AREA/lld tools/.
    #mv DISABLED_AREA/lldb tools/.
    mv DISABLED_AREA/libcxx projects/.
    mv DISABLED_AREA/libcxxabi projects/.
    mv DISABLED_AREA/openmp projects/.

    # Stage2 compile now
    pushd sol-stage2
    cmake .. \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_C_FLAGS_RELEASE="$CFLAGS" \
        -DCMAKE_CXX_FLAGS_RELEASE="$CXXFLAGS" \
        -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DLLVM_INSTALL_UTILS=ON \
        -DLLVM_LIBDIR_SUFFIX=%LIBSUFFIX% \
        -DLLVM_TARGET_ARCH=$_LLVM_ARCH \
        -DLLVM_BINUTILS_INCDIR=/usr/local/include \
        -DLLVM_DEFAULT_TARGET_TRIPLE=$_LLVM_TRIPLE \
        -DLLVM_ENABLE_FFI=ON \
        -DLLVM_ENABLE_ZLIB=ON \
        -DLLVM_BUILD_DOCS=OFF \
        -DLLVM_ENABLE_RTTI=OFF \
        -DLLVM_ENABLE_ASSERTIONS=OFF \
        -DLLVM_ENABLE_CXX1Y=ON \
        -DPYTHON_EXECUTABLE=/usr/bin/python2 \
        -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so \
        -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 \
        -DLLDB_USE_SYSTEM_SIX=ON \
        -DENABLE_LINKER_BUILD_ID=ON \
        -DLLVM_INCLUDEDIR=/usr/local/include \
        -DLLVM_ENABLE_PIC=ON \
        -DLLVM_TARGETS_TO_BUILD="host;AMDGPU;BPF" \
        -DLLVM_BUILD_LLVM_DYLIB=ON \
        -DLLVM_LINK_LLVM_DYLIB=ON \
        -G Ninja
build      : |
    # Build it
    unset LD_AS_NEEDED
    LC_ALL=en_US.UTF-8 ninja %JOBS% -C sol-stage2 -v

    # Now build 32-bit llvm bits
    mkdir sol-stage2-emul32
    export _LLVM_TRIPLE="i686-pc-linux-gnu"
    export _LLVM_ARCH="i686"
    export _LLVM_FLAGS_FINAL="-march=i686 -mtune=generic -gline-tables-only -O3 -fstack-protector -pipe -DNDEBUG"

    # Before we start emul32, disable lldb/lld
    mv tools/lld DISABLED_AREA/lld
    #mv tools/lldb DISABLED_AREA/lldb

    STAGE2DIR=$(realpath ./sol-stage2/bin)
    pushd sol-stage2-emul32
    # We need to preserve the symlink in the name during invocation
    export CC="${STAGE2DIR}/clang -m32"
    export CXX="${STAGE2DIR}/clang++ -m32"

    export CFLAGS="$_LLVM_FLAGS_FINAL"
    export CXXFLAGS="$_LLVM_FLAGS_FINAL"
    unset LDFLAGS
    unset LD_AS_NEEDED

    # Even though we want to disable stuff, the libLLVM-$VERSION.so won't be installed..
    cmake .. \
        -DLLVM_BUILD_DOCS=OFF \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_C_FLAGS_RELEASE="$CFLAGS" \
        -DCMAKE_CXX_FLAGS_RELEASE="$CXXFLAGS" \
        -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DLLVM_LIBDIR_SUFFIX=32 \
        -DLLVM_TARGET_ARCH=$_LLVM_ARCH \
        -DLLVM_DEFAULT_TARGET_TRIPLE=$_LLVM_TRIPLE \
        -DLLVM_ENABLE_FFI=ON \
        -DLLVM_ENABLE_ZLIB=ON \
        -DLLVM_ENABLE_RTTI=OFF \
        -DLLVM_ENABLE_ASSERTIONS=OFF \
        -DLLVM_ENABLE_CXX1Y=ON \
        -DENABLE_LINKER_BUILD_ID=ON \
        -DLLVM_INCLUDEDIR=/usr/local/include \
        -DLLVM_ENABLE_PIC=ON \
        -DLLVM_TARGETS_TO_BUILD="host;AMDGPU;BPF" \
        -DLLVM_BUILD_LLVM_DYLIB=ON \
        -DLLVM_LINK_LLVM_DYLIB=ON \
        -G Ninja
    LC_ALL=en_US.UTF-8 ninja %JOBS% -v
install    : |
    # Install 32-bit
    DESTDIR="%installroot%" LC_ALL=en_US.UTF-8 ninja %JOBS% -C sol-stage2-emul32 install -v
    mv $installdir/usr/local/include/llvm/Config/llvm-config.h $installdir/usr/local/include/llvm/Config/llvm-config-32.h

    # Restore directories for stage2 emul32
    mv DISABLED_AREA/lld tools/.
    #mv DISABLED_AREA/lldb tools/.

    # Allow stage2 native to overwrite any stage2-emul32 files
    DESTDIR="%installroot%" LC_ALL=en_US.UTF-8 ninja %JOBS% -C sol-stage2 install -v
    mv $installdir/usr/local/include/llvm/Config/llvm-config.h $installdir/usr/local/include/llvm/Config/llvm-config-64.h

    # Finally add our compatibility header
    install -m 00644 $pkgfiles/llvm-config.h $installdir/usr/local/include/llvm/Config/llvm-config.h

    install -d -D -m 00755 $installdir/usr/local/lib64/bfd-plugins
    ln -sv ../LLVMgold.so $installdir/usr/local/lib64/bfd-plugins/.

    # Do NOT include libgomp*, it will conflict with libgomp
    rm $installdir/usr/local/lib{32,64}/libgomp.*
