name       : python-contextlib2
version    : 0.5.5
release    : 3
source     :
    - https://github.com/jazzband/contextlib2/archive/v0.5.5.tar.gz : 613569263db0271f34c8484792360272a731f2185567c31c8118e9c994412170
license    : Python-2.0
component  : programming.python
summary    : A backport of the standard library's contextlib module to earlier Python versions
description: |
    contextlib2 is a backport of the standard library's contextlib module to earlier Python versions. 
build      : |
    %python3_setup
install    : |
    %python3_install
