name       : python-semanticversion
version    : 2.6.0
release    : 2
source     :
    - https://github.com/rbarrois/python-semanticversion/archive/v2.6.0.tar.gz : 110d9c75dc9670a188ab820503c6b40ea4ab3f1450a0aee5a90a24fd60aef358
license    : BSD-2-Clause
component  : programming.python
summary    : Semantic version comparison for Python
description: |
    This small python library provides a few tools to handle SemVer in Python. It follows strictly the 2.0.0 version of the SemVer scheme.
builddeps  :
    - python-pytest
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        rm tests/test_django.py
        py.test
    popd

    pushd $PKG_BUILD_DIR/py3build
        rm tests/test_django.py
        py.test
    popd
