name       : python-absl-py
version    : 0.7.0
release    : 2
source     :
    - https://github.com/abseil/abseil-py/archive/pypi-v0.7.0.tar.gz : 595726be4bf3f7e6d64a1a255fa03717b693c01b913768abd52649cbb7ddf2bd
license    : Apache-2.0
component  : programming.python
summary    : Abseil Python Common Libraries
description: |
    A collection of Python library code from Google's Python code base for building Python applications.
rundeps    :
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
