name       : python-tqdm
version    : 4.30.0
release    : 2
source     :
    - https://github.com/tqdm/tqdm/archive/v4.30.0.tar.gz : 5a4681e05a0b2b47d0aa0bf1ca512365f21f9381451c52bccf8d0370f7b51c20
license    : 
    - MIT
    - MPL-2.0
component  : programming.python
summary    : A fast, extensible progress bar for Python and CLI
description: |
    A fast, extensible progress bar for Python and CLI
build      : |
    %python3_setup
install    : |
    %python3_install
