name       : cudnn
version    : 7.6.2
release    : 8
source     :
    - https://p-def7.pcloud.com/cBZXBwcpYZso1mgYZ8kOdZXZWeT5N7Z2ZZJsXZkZKSg6PZx5ZtVZi5Z7JZE0ZCJZQ0ZLkZOXZH0Z05ZvXZ27ZkFZN4zc7ZwrUkEhjwVXYQL9oIVe5drFWu77ok/cudnn-10.1-linux-x64-v7.6.2.24.tgz : afbfd6a61e774beb3851742452c007de4f65f8ec0592d583bc6806f8d386cd1f
license    : EULA
component  : programming.library
summary    : The NVIDIA CUDA® Deep Neural Network library
description: |
    NVIDIA cuDNN is a GPU-accelerated library of primitives for deep neural networks.
strip      : no
install    : |
    install -dm00755 $installdir/%libdir%/cuda/include $installdir/%libdir%/cuda/lib64
    install -Dm00644 include/cudnn.h $installdir/%libdir%/cuda/include/cudnn.h
    cp -r lib64/lib* $installdir/%libdir%/cuda/lib64
