name       : cudnn
version    : 7.5.0
release    : 3
source     :
    - https://p-def2.pcloud.com/cBZRsMLVLZPawCjLZ8kOdZXZ0plkA7Z2ZZIGzZkZimSkMZRkZOXZmZa5ZiXZNVZVJZSVZEkZnXZw5ZRXZv0ZP7Z0REd7ZLv4RSclgFF7aOXNbtDYan4H8CFNV/cudnn-10.1-linux-x64-v7.5.0.56.tgz : c31697d6b71afe62838ad2e57da3c3c9419c4e9f5635d14b683ebe63f904fbc8
license    : EULA
component  : programming.library
summary    : The NVIDIA CUDA® Deep Neural Network library
description: |
    NVIDIA cuDNN is a GPU-accelerated library of primitives for deep neural networks.
strip      : no
install    : |
    install -dm00755 $installdir/usr/include/cuda $installdir/%libdir%/cuda/include $installdir/%libdir%/cuda/lib64
    install -Dm00644 include/cudnn.h $installdir/%libdir%/cuda/include/cudnn.h
    ln -sf %libdir%/cuda/include/cudnn.h $installdir/usr/include/cuda/
    cp -r lib64/lib* $installdir/%libdir%/cuda/lib64
    for f in $installdir/%libdir%/cuda/lib64/lib*; do
        ln -sf %libdir%/cuda/lib64/`basename $f` $installdir/%libdir%
    done

    install -dm00755 $installdir/%libdir%/pkgconfig
    install -Dm00644 $pkgfiles/cudnn.pc $installdir/%libdir%/pkgconfig/cudnn.pc
