name       : cudnn
version    : 7.6.1
release    : 7
source     :
    - https://p-def7.pcloud.com/cBZjzvto8ZD6XjfQZ8kOdZXZDU8IA7Z2ZZJsXZkZIv3KPZf5ZtJZz5ZFJZr0Z3XZOXZmXZB7ZH0ZBkZAZ8VZcZh5m37ZEN45GDta1oVjDdPrBXetfBLfwjNk/cudnn-10.1-linux-x64-v7.6.1.34.tgz : 9885e38e71fa9844b3e4fb7c7211af41b24c9f76a9014f9d5e1768ddff2087dc
license    : EULA
component  : programming.library
summary    : The NVIDIA CUDA® Deep Neural Network library
description: |
    NVIDIA cuDNN is a GPU-accelerated library of primitives for deep neural networks.
strip      : no
install    : |
    install -dm00755 $installdir/%libdir%/cuda/include $installdir/%libdir%/cuda/lib64
    install -Dm00644 include/cudnn.h $installdir/%libdir%/cuda/include/cudnn.h
    cp -r lib64/lib* $installdir/%libdir%/cuda/lib64
