name       : bazel
version    : 0.19.2
release    : 4
source     :
    - https://github.com/bazelbuild/bazel/releases/download/0.19.2/bazel-0.19.2-dist.zip : 11234cce4f6bdc62c3ac688f41c7b5c178eecb6f7e2c4ba0bcf00ba8565b1d19
license    : Apache-2.0
component  : programming.tools
summary    : A fast, scalable, multi-language and extensible build system
description: |
    A fast, scalable, multi-language and extensible build system
strip      : no
networking : yes
builddeps  :
    - openjdk-8
rundeps    :
    - openjdk-8
build      : |
    bash compile.sh
    output/bazel build \
        --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8 \
        --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8 \
        //scripts:bazel-complete.bash
    output/bazel shutdown
install    : |
    install -Dm00755 output/bazel $installdir/usr/bin/bazel
    install -Dm00644 $workdir/bazel-bin/scripts/bazel-complete.bash $installdir/usr/share/bash-completion/completions/bazel
    install -Dm00644 $workdir/scripts/zsh_completion/_bazel $installdir/usr/share/zsh/site-functions/_bazel
