name       : bazel
version    : 0.26.1
release    : 8
source     :
    - https://github.com/bazelbuild/bazel/releases/download/0.26.1/bazel-0.26.1-dist.zip : c0e94f8f818759f3f67af798c38683520c540f469cb41aea8f5e5a0e43f11600
license    : Apache-2.0
component  : programming.tools
summary    : A fast, scalable, multi-language and extensible build system
description: |
    A fast, scalable, multi-language and extensible build system
debug      : no
strip      : no
networking : yes
builddeps  :
    - openjdk-8
rundeps    :
    - openjdk-8
build      : |
    bash compile.sh
    output/bazel build //scripts:bazel-complete.bash
    output/bazel shutdown
install    : |
    install -Dm00755 output/bazel $installdir/usr/bin/bazel
    install -Dm00644 $workdir/bazel-bin/scripts/bazel-complete.bash $installdir/usr/share/bash-completion/completions/bazel
    install -Dm00644 $workdir/scripts/zsh_completion/_bazel $installdir/usr/share/zsh/site-functions/_bazel
