name       : starship
version    : 0.40.1
release    : 1
source     :
    - https://github.com/starship/starship/archive/v0.40.1.tar.gz : df4318d901eaafccebfc4eefcfff03a8bcbe3c0f3a9bc896b1c54c9a3608aaf7
license    : ISC
component  : system.utils
summary    : The minimal, blazing-fast, and infinitely customizable prompt for any shell!
description: |
    The minimal, blazing-fast, and infinitely customizable prompt for any shell!
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/starship $installdir/usr/bin/starship
