name       : yapf
version    : 0.26.0
release    : 1
source     :
    - https://github.com/google/yapf/archive/v0.26.0.tar.gz : 1cc7e6148024bf85a9f4ddf3808d948a0b9be64c945d439963113ab239a07c16
license    : Apache-2.0
component  : programming.python
summary    : A formatter for Python files
description: |
    Yapf is based off of clang-format and reformats the code to the best formatting that conforms to the style guide, even if the original code didn't violate the style guide.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
