name       : yapf
version    : 0.28.0
release    : 2
source     :
    - https://github.com/google/yapf/archive/v0.28.0.tar.gz : e1d968c273ccd5c0461d9e487a5fd87b546f844212204f5b025231be7674adc6
license    : Apache-2.0
component  : programming.python
summary    : A formatter for Python files
description: |
    Yapf is based off of clang-format and reformats the code to the best formatting that conforms to the style guide, even if the original code didn't violate the style guide.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
