name       : python-tensorflow-probability
version    : 0.7
release    : 2
source     :
    - https://github.com/tensorflow/probability/archive/v0.7.tar.gz : aa938dfb84e68e1f645a5543ed2e7eeb2bdc260f751e5a4e8434b25062b7a25f
license    : Apache-2.0
component  : programming.python
summary    : Probabilistic reasoning and statistical analysis in TensorFlow
description: |
    TensorFlow Probability is a library for probabilistic reasoning and statistical analysis in TensorFlow. As part of the TensorFlow ecosystem, TensorFlow Probability provides integration of probabilistic methods with deep networks, gradient-based inference via automatic differentiation, and scalability to large datasets and models via hardware acceleration (e.g., GPUs) and distributed computation.
builddeps  :
    - bazel
    - python-wheel
rundeps    :
    - numpy
    - python-cloudpickle
    - python-decorator
    - python-six
setup      : |
    %patch -p1 < $pkgfiles/use_python3.patch
    bazel build --copt=-march=haswell --copt=-mtune=haswell --copt=-g2 --copt=-O3 :pip_pkg
    bazel shutdown
build      : |
    mkdir -p $PKG_BUILD_DIR/build
    ./bazel-bin/pip_pkg $PKG_BUILD_DIR/build
install    : |
    pip3 install --no-deps --root=$installdir $PKG_BUILD_DIR/build/*.whl
