name       : sioyek
version    : 1.3.0
release    : 3
source     :
    - https://github.com/ahrm/sioyek/archive/refs/tags/v1.3.0.tar.gz : 153876cecb75c32bed5469a86f24e7f14ea885711dacbac0072e91594d9f9235
license    : GPL-3.0-or-later
component  : office.viewers
summary    : A PDF viewer designed for reading research papers and technical books
description: |
    Sioyek is a PDF viewer designed for reading research papers and technical books.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt53DCore)
    - pkgconfig(jbig2dec)
    - pkgconfig(freetype2)
    - pkgconfig(libopenjp2)
    - pkgconfig(libjpeg)
    - mupdf-devel
    - pkgconfig(harfbuzz)
setup      : |
    sed -i 's/-lmupdf-third -lmupdf-threads -lharfbuzz/-lmupdf-threads -lharfbuzz/' pdf_viewer_build_config.pro
    sed -i 's/\/etc\/sioyek/\/usr\/share\/sioyek/' pdf_viewer/main.cpp
build      : |
    %qmake DEFINES+="LINUX_STANDARD_PATHS" pdf_viewer_build_config.pro
    %make
install    : |
    %make_install prefix=%PREFIX% INSTALL_ROOT="%installroot%"

    install -Dm00644 resources/sioyek.1 $installdir/usr/share/man/man1/sioyek.1
    install -Dm00644 pdf_viewer/prefs.config $installdir/usr/share/sioyek/prefs.config
    install -Dm00644 pdf_viewer/keys.config $installdir/usr/share/sioyek/keys.config
    install -Dm00644 pdf_viewer/shaders/* -t $installdir/usr/share/sioyek/shaders
    install -Dm00644 tutorial.pdf $installdir/usr/share/sioyek/tutorial.pdf
