name       : nvidia-optimus-manager
version    : 0.2.1
release    : 4
source     :
    - https://github.com/xulongwu4/nvidia-optimus-manager/archive/v0.2.1.tar.gz : 64638bbdaf6fe57748917e42165e878a5089e77097335fc68e824d4c43dd5e10
license    : MIT
component  :
    - system.utils
    - lightdm-integration : desktop.lightdm
summary    : 
    - A python script to manage the status of NVIDIA graphics card on an Optimus setup for Solus linux
    - lightdm-integration : nvidia-optimus-manager integration for LightDM
description: |
    A python script to manage the status of NVIDIA graphics card on an Optimus setup for Solus linux
rundeps  :
    - pciutils
patterns   :
    - lightdm-integration :
        - /usr/share/lightdm/lightdm.conf.d/99-nvidia.conf
install    : |
    install -Dm00755 nvidia-optimus-manager $installdir/usr/bin/nvidia-optimus-manager
    install -dm00755 $installdir/usr/share/lightdm/lightdm.conf.d
    install -Dm00644 99-nvidia.conf $installdir/usr/share/lightdm/lightdm.conf.d/99-nvidia.conf
    install -dm00755 $installdir/%libdir%/systemd/system
    install -Dm00644 nvidia-optimus-autoconfig.service $installdir/%libdir%/systemd/system/nvidia-optimus-autoconfig.service
    install -dm00755 $installdir/%libdir%/systemd/system/multi-user.target.wants
    ln -sv ../nvidia-optimus-autoconfig.service $installdir/%libdir%/systemd/system/multi-user.target.wants/.
