name       : python-tensorflow-serving-api
version    : 1.12.0
release    : 2
source     :
    - https://github.com/tensorflow/serving/archive/1.12.0.tar.gz : 67f0f7630f8582f8997eae4da3a9a7082b9e4448826d3bbc5012459ca3a01440
license    : Apache-2.0
component  : programming.python
summary    : A flexible, high-performance serving system for machine learning models
description: |
    TensorFlow Serving is an open-source software library for serving machine learning models. It deals with the inference aspect of machine learning, taking models after training and managing their lifetimes, providing clients with versioned access via a high-performance, reference-counted lookup table.
networking : yes
builddeps  :
    - bazel
    - python-wheel
setup      : |
    sed -i '78s/python/python3/' tensorflow_serving/tools/pip_package/build_pip_package.sh
build      : |
    bazel build //tensorflow_serving/tools/pip_package:build_pip_package
    bazel-bin/tensorflow_serving/tools/pip_package/build_pip_package /tmp
    bazel shutdown
install    : |
    pip3 install --no-deps --root=$installdir /tmp/tensorflow_serving*.whl
