name       : ms-teams
version    : 1.4.00.13653
release    : 4
source     :
    - https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.4.00.13653_amd64.deb : 5b4217fab3df145b1a37c53d138d87713786f290805a90fc276434770692a4cf
license    : Distributable
component  : network.clients
summary    : Microsoft Teams for Linux
description: |
    Linux desktop client for Microsoft Teams
strip      : no
extract    : no
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(xkbfile)
    - pkgconfig(xscrnsaver)
setup      : |
    ar xf $sources/teams_${version}_amd64.deb
    tar xf data.tar.xz
install    : |
    install -dm00755 $installdir
    cp -r usr $installdir

    # Link to system libraries
    rm $installdir/usr/share/teams/lib{EGL,GLESv2}.so
    ln -s %libdir%/lib{EGL,GLESv2}.so $installdir/usr/share/teams

    # Clean up
    find $installdir/usr -type d -empty -print -delete
