name       : python-protobuf
version    : 3.6.1
release    : 9
source     :
    - https://files.pythonhosted.org/packages/1b/90/f531329e628ff34aee79b0b9523196eb7b5b6b398f112bb0c03b24ab1973/protobuf-3.6.1.tar.gz : 1489b376b0f364bcc6f89519718c057eb191d7ad6f1b395ffd93d1aa45587811
license    : BSD-3-Clause
homepage   : https://pypi.python.org/pypi/protobuf/
component  : programming.python
summary    : Python bindings for Protobuf
description: |
    Python bindings for Protobuf
builddeps  :
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - protobuf
build      : |
    %python_setup --cpp_implementation
    %python3_setup --cpp_implementation
install    : |
    %python_install --cpp_implementation
    %python3_install --cpp_implementation
