name       : python-pytools
version    : 2019.1
release    : 2
source     :
    - https://github.com/inducer/pytools/archive/v2019.1.tar.gz : ad27d45aee6501820a9dc5af7ec2986afedfaac31e33d6a6bb4ad70142dbefa4
license    : MIT
component  : programming.python
summary    : A collection of tools for Python
description: |
    Pytools is a big bag of things that are "missing" from the Python standard library. This is mainly a dependency of my other software packages, and is probably of little interest to you unless you use those.
rundeps    :
    - numpy
    - python-appdirs
    - python-decorator
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
