name       : python-astor
version    : 0.7.1
release    : 2
source     :
    - https://github.com/berkerpeksag/astor/archive/0.7.1.tar.gz : 444eba3e3012ae9ba9276df02a40bf694b9e68f6a95d36062b71aa26f1f3ff6c
license    : BSD-3-Clause
component  : programming.python
summary    : Python AST read/write
description: |
    Astor is designed to allow easy manipulation of Python source via the AST.
build      : |
    %python3_setup
install    : |
    %python3_install
