name       : python-tensorflow-estimator
version    : 1.13.0
release    : 1
source     :
    - https://github.com/tensorflow/estimator/archive/v1.13.0.tar.gz : a787b150ff436636df723e507019c72a5d6486cfe506886279d380166953f12f
license    : Apache-2.0
component  : programming.python
summary    : TensorFlow Estimator
description: |
    TensorFlow Estimator is a high-level TensorFlow API that greatly simplifies machine learning programming. Estimators encapsulate training, evaluation, prediction, and exporting for your model.
builddeps  :
    - bazel
    - python-wheel
    - tensorflow-cuda
build      : |
    # This is dirty and it is due to bazel by default use "/usr/bin/env python"
    mkdir -p $workdir/python_binary
    ln -s $(which python3) $workdir/python_binary/python
    export PATH=$workdir/python_binary:$PATH
    echo $(which python)
    bazel build --action_env=PATH //tensorflow_estimator/tools/pip_package:build_pip_package
    bazel-bin/tensorflow_estimator/tools/pip_package/build_pip_package /tmp
    bazel shutdown
install    : |
    pip3 install --no-deps --root=$installdir /tmp/tensorflow_estimator*.whl
