name       : tensorrt
version    : 5.1.5.0
release    : 6
source     :
    - https://p-def5.pcloud.com/cBZdBhEi4ZKCRCb8Z8kOdZXZO7a9A7Z2ZZJsXZkZWh606Z87ZDJZw7ZPVZjkZxkZpXZgJZRVZRXZU0Zu0ZV5Z3VZQoPI7ZTjB9yxYONVViyBCj32Mj4Rxd5XJk/TensorRT-5.1.5.0.Ubuntu-18.04.2.x86_64-gnu.cuda-10.1.cudnn7.5.tar.gz : d247fd1270ea20bda896fdd8dff6ae320b981addfa071c3a1246b7c27023e011
license    : EULA
component  : programming.library
summary    : A platform for high-performance deep learning inference
description: |
    NVIDIA TensorRT™ is a platform for high-performance deep learning inference.
strip      : no
builddeps  :
    - pkgconfig(cuda)
    - pkgconfig(cudnn)
rundeps    :
    - pycuda
install    : |
    install -dm00755 $installdir/usr/include
    install -Dm00644 -t $installdir/usr/include include/*.h

    install -dm00755 $installdir/%libdir%
    cp -r lib/lib* $installdir/%libdir%
    rm -rv $installdir/%libdir%/libprotobuf*.a

    install -dm00755 $installdir/usr/bin
    install -Dm00755 bin/trtexec $installdir/usr/bin

    pushd python
    pip3 install --no-deps --root="%installroot%" tensorrt-*cp36*.whl
    popd

    pushd uff
    pip3 install --no-deps --root="%installroot%" uff-*.whl
    popd

    pushd graphsurgeon
    pip3 install --no-deps --root="%installroot%" graphsurgeon-*.whl
    popd

    install -dm00755 $installdir/usr/share/doc/tensorrt
    cp -r doc $installdir/usr/share/doc/tensorrt
    install -Dm00644 TensorRT-Release-Notes.pdf $installdir/usr/share/doc/tensorrt

    install -dm00755 $installdir/usr/share/tensorrt
    cp -r data/ $installdir/usr/share/tensorrt
    cp -r samples/ $installdir/usr/share/tensorrt
