name       : dnnl
version    : 1.1.1
release    : 1
source     :
    - https://github.com/intel/mkl-dnn/archive/v1.1.1.tar.gz : a31b08a89473bfe3bd6ed542503336d21b4177ebe4ccb9a97810808f634db6b6
license    : Apache-2.0
component  : programming.library
avx2       : yes
summary    : Deep Neural Network Library (DNNL)
description: |
    Deep Neural Network Library (DNNL) is an open-source performance library for deep learning applications. The library includes basic building blocks for neural networks optimized for Intel Architecture Processors and Intel Processor Graphics. DNNL is intended for deep learning applications and framework developers interested in improving application performance on Intel CPUs and GPUs.
setup      : |
    %patch -p1 < $pkgfiles/mkldnn_cmake_path.patch
    %cmake_ninja -DDNNL_ENABLE_PRIMITIVE_CACHE=ON -DDNNL_ARCH_OPT_FLAGS=""
build      : |
    %ninja_build
install    : |
    %ninja_install

    if [[ ! -z "${AVX2BUILD}" ]]; then
        unlink $installdir/%libdir%/libdnnl.so
        unlink $installdir/%libdir%/libmkldnn.so
    fi
check      : |
    %ninja_check
