name       : dnnl
version    : 1.1
release    : 1
source     :
    - https://github.com/intel/mkl-dnn/archive/v1.1.tar.gz : c5aac67e5ed4d95fe9943f835df49bbe6d608507780787c64aa620bdbd2171ba
license    : Apache-2.0
component  : programming.library
optimize   :
    - speed
avx2       : yes
summary    : Deep Neural Network Library (DNNL)
description: |
    Deep Neural Network Library (DNNL) is an open-source performance library for deep learning applications. The library includes basic building blocks for neural networks optimized for Intel Architecture Processors and Intel Processor Graphics. DNNL is intended for deep learning applications and framework developers interested in improving application performance on Intel CPUs and GPUs.
setup      : |
    %patch -p1 < $pkgfiles/mkldnn_cmake_path.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
