name       : python-h5py
version    : 2.9.0
release    : 3
source     :
    - https://github.com/h5py/h5py/archive/2.9.0.tar.gz : 49d593c07a3a4cb87ed421f502e34368b98282a4ac6d4388379aab80b11c7924
license    : BSD-3-Clause
component  : programming.python
summary    : A Pythonic interface to the HDF5 binary data format
description: |
    The h5py package provides both a high- and low-level interface to the HDF5 library from Python. The low-level interface is intended to be a complete wrapping of the HDF5 API, while the high-level component supports access to HDF5 files, datasets and groups using established Python and NumPy concepts. A strong emphasis on automatic conversion between Python (Numpy) datatypes and data structures and their HDF5 equivalents vastly simplifies the process of reading and writing data from Python.
builddeps  :
    - cython
    - hdf5-devel
    - numpy
    - python-pkgconfig
    - python-six
rundeps    :
    - numpy
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
