name       : python-grpcio
version    : 1.18.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/90/2e/f432e69f86961393c22a6c4490aafdbb94533deba33f5ea2d5651770aa21/grpcio-1.18.0.tar.gz : abe825aa49e6239d5edf4e222c44170d2c7f6f4b1fd5286b4756a62d8067e112
license    : Apache-2.0
component  : programming.python
summary    : HTTP/2-based RPC framework
description: |
    HTTP/2-based RPC framework
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
