name       : cuda
version    : 10.0.130
release    : 2
source     :
    - https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_410.48_linux : 92351f0e4346694d0fcb4ea1539856c9eb82060c25654463bfd8574ec35ee39a
extract    : no
license    : EULA
component  : programming.library
summary    : NVIDIA's GPU programming toolkit
description: |
    CUDA® is a parallel computing platform and programming model developed by NVIDIA for general computing on graphical processing units (GPUs).
libsplit   : no
strip      : no
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freeglut)
    - pkgconfig(glu)
    - pkgconfig(libpulse)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xrandr)
    - chrpath
rundeps    :
    - openjdk-8
patterns   :
    - devel : /usr/lib64/cuda/samples
setup      : |
    CUDA_INSTALL_FILE=$(basename $sources/cuda_${version}_*_linux*)
    sh $sources/$CUDA_INSTALL_FILE --extract=$workdir
build      : |
    ./cuda-linux.${version}-*.run -noprompt -nosymlink -no-man-page -prefix=$PKG_BUILD_DIR/cuda_build
    ./cuda-samples.${version}-*.run -noprompt -prefix=$PKG_BUILD_DIR/cuda_build/samples -cudaprefix=%libdir%/cuda

    pushd $PKG_BUILD_DIR/cuda_build
    %patch -p1 < $pkgfiles/gcc-8.patch
    popd
install    : |
    install -dm00755 $installdir/%libdir%
    mv $PKG_BUILD_DIR/cuda_build $installdir/%libdir%/cuda

    pushd $installdir/%libdir%/cuda

    # Adjust path for NSight plugin
    sed -i -e 's|`dirname $0`/..|%libdir%/cuda|g' bin/nsight_ee_plugins_manage.sh

    # Java stuff
    # jre
    rm -rfv jre
    sed -i -e '/^-vm/d' -e '/jre\/bin\/java/d' libnsight/nsight.ini libnvvp/nvvp.ini
    #sed -i -e 's|../jre/bin/java|/usr/bin/java|g' libnsight/nsight.ini libnvvp/nvvp.ini

    install -dm00755 $installdir/usr/share/pixmaps
    install -Dm00644 libnsight/icon.xpm $installdir/usr/share/pixmaps/nsight.xpm
    install -Dm00644 libnvvp/icon.xpm $installdir/usr/share/pixmaps/nvvp.xpm
    #mv libnsight $installdir/%libdir%/nsight
    #mv libnvvp $installdir/%libdir%/nvvp
    #mv nsightee_plugins $installdir/%libdir%/nsight/
    rm -v $installdir/%libdir%/cuda/bin/nsight
    rm -v $installdir/%libdir%/cuda/bin/nvvp
    install -dm00755 $installdir/usr/bin
    ln -sf %libdir%/cuda/libnsight/nsight $installdir/usr/bin
    ln -sf %libdir%/cuda/libnvvp/nvvp $installdir/usr/bin
    install -dm00755 $installdir/usr/share/applications
    install -Dm00644 $pkgfiles/nsight.desktop $installdir/usr/share/applications/nsight.desktop
    install -Dm00644 $pkgfiles/nvvp.desktop $installdir/usr/share/applications/nvvp.desktop

    # Binaries
    find $installdir/%libdir%/cuda/{bin,samples} -type f -name "*install*" -delete
    rm -v $installdir/%libdir%/cuda/bin/nvcc.profile
    install -Dm00644 $pkgfiles/nvcc.profile $installdir/%libdir%/cuda/bin/nvcc.profile
    for f in $installdir/%libdir%/cuda/bin/*; do
        ln -sf %libdir%/cuda/bin/`basename $f` $installdir/usr/bin
    done

    # Docs
    install -dm00755 $installdir/usr/share/doc/cuda
    mv doc/html $installdir/usr/share/doc/cuda
    mv doc/pdf $installdir/usr/share/doc/cuda
    install -dm00755 $installdir/usr/share/man/man{1,7}
    install -Dm00644 -t $installdir/usr/share/man/man1 doc/man/man1/*
    install -Dm00644 -t $installdir/usr/share/man/man7 doc/man/man7/*
    rm -rfv doc

    # Header files
    find $installdir/%libdir%/cuda/include -type f -print0 | xargs -0 chmod 644
    install -dm00755 $installdir/usr/include/cuda
    for f in $installdir/%libdir%/cuda/include/*; do
        ln -sf %libdir%/cuda/include/`basename $f` $installdir/usr/include/cuda
    done

    # Libraries
    # Remove OpenCL
    rm -v $installdir/%libdir%/cuda/lib64/libOpenCL.so*
    # We don't use the libraries in `stubs` subdir
    rm -rfv $installdir/%libdir%/cuda/lib64/stubs
    for f in lib64/lib*.so* lib64/lib*.a; do
        ln -sf %libdir%/cuda/lib64/`basename $f` $installdir/%libdir%
    done

    # nvvm
    # Remove RUNPATH on binaries
    chrpath -d $installdir/%libdir%/cuda/nvvm/bin/cicc
    ln -sf %libdir%/cuda/nvvm/bin/cicc $installdir/usr/bin
    ln -sf %libdir%/cuda/nvvm/include/nvvm.h $installdir/usr/include/cuda
    for f in nvvm/lib64/lib*.so*; do
        ln -sf %libdir%/cuda/nvvm/lib64/`basename $f` $installdir/%libdir%
    done

    # pkgconfig
    install -dm00755 $installdir/usr/lib64/pkgconfig
    install -Dm00644 -t $installdir/usr/lib64/pkgconfig $pkgfiles/*.pc

    # samples
    find $installdir/%libdir%/cuda/samples -type f -name "findgllib.mk" -print0 | 
        xargs -0 sed -i '57i\    GLPATH    ?= /usr/lib64/nvidia\n    GLLINK    ?= -L/usr/lib64/nvidia\n    DFLT_PATH ?= /usr/lib64'

    # extras/{CUPTI,Debugger}
    for dir in CUPTI Debugger; do
        install -dm00755 $installdir/usr/include/cuda/$dir
        for f in $installdir/%libdir%/cuda/extras/$dir/include/*; do
            ln -sf %libdir%/cuda/extras/$dir/include/`basename $f` $installdir/usr/include/cuda/$dir
        done
        for f in $installdir/%libdir%/cuda/extras/$dir/lib64/*; do
            ln -sf %libdir%/cuda/extras/$dir/lib64/`basename $f` $installdir/%libdir%
        done
    done

    popd

    # Clean up
    find $installdir/%libdir%/cuda -name "*.bat" -delete
    # Clean empty directories
    find $installdir/%libdir%/cuda -type d -empty -delete
