name       : cuda
version    : 10.1.105
release    : 4
source     :
    - https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.39_linux.run : 33ac60685a3e29538db5094259ea85c15906cbd0f74368733f4111eab6187c8f
extract    : no
license    : EULA
component  : programming.library
summary    : NVIDIA's GPU programming toolkit
description: |
    CUDA® is a parallel computing platform and programming model developed by NVIDIA for general computing on graphical processing units (GPUs).
strip      : no
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freeglut)
    - pkgconfig(glu)
    - pkgconfig(libpulse)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xrandr)
rundeps    :
    - openjdk-8
patterns   :
    - devel : /usr/lib64/cuda/samples
build      : |
    CUDA_INSTALL_FILE=$(basename $sources/cuda_${version}_*_linux*)
    sh $sources/$CUDA_INSTALL_FILE --extract=$workdir
    #./cuda-linux.${version}-*.run -noprompt -nosymlink -no-man-page -prefix=$PKG_BUILD_DIR/cuda_build
    #./cuda-samples.${version}-*.run -noprompt -prefix=$PKG_BUILD_DIR/cuda_build/samples -cudaprefix=%libdir%/cuda
install    : |
    install -dm00755 $installdir/%libdir% $installdir/usr/bin
    mv $workdir/cuda-toolkit $installdir/%libdir%/cuda

    pushd $installdir/%libdir%/cuda

    # Adjust path for NSight plugin
    sed -i -e 's|`dirname $0`/..|%libdir%/cuda|g' bin/nsight_ee_plugins_manage.sh

    # Java stuff
    # jre
    rm -rfv jre
    sed -i -e '/^-vm/d' -e '/jre\/bin\/java/d' libnsight/nsight.ini libnvvp/nvvp.ini
    #sed -i -e 's|../jre/bin/java|/usr/bin/java|g' libnsight/nsight.ini libnvvp/nvvp.ini

    install -dm00755 $installdir/usr/share/pixmaps
    install -Dm00644 libnsight/icon.xpm $installdir/usr/share/pixmaps/nsight.xpm
    install -Dm00644 libnvvp/icon.xpm $installdir/usr/share/pixmaps/nvvp.xpm
    #mv libnsight $installdir/%libdir%/nsight
    #mv libnvvp $installdir/%libdir%/nvvp
    #mv nsightee_plugins $installdir/%libdir%/nsight/
    rm -v $installdir/%libdir%/cuda/bin/nsight
    rm -v $installdir/%libdir%/cuda/bin/nvvp
    ln -sf %libdir%/cuda/libnsight/nsight $installdir/usr/bin
    ln -sf %libdir%/cuda/libnvvp/nvvp $installdir/usr/bin
    install -dm00755 $installdir/usr/share/applications
    install -Dm00644 $pkgfiles/nsight.desktop $installdir/usr/share/applications/nsight.desktop
    install -Dm00644 $pkgfiles/nvvp.desktop $installdir/usr/share/applications/nvvp.desktop

    # Binaries
    find $installdir/%libdir%/cuda/bin -type f -name "*install*" -delete
    rm -v $installdir/%libdir%/cuda/bin/nvcc.profile
    install -Dm00644 $pkgfiles/nvcc.profile $installdir/%libdir%/cuda/bin/nvcc.profile
    for f in $installdir/%libdir%/cuda/bin/*; do
        ln -sf %libdir%/cuda/bin/`basename $f` $installdir/usr/bin
    done

    # Docs
    install -dm00755 $installdir/usr/share/doc/cuda
    mv doc/html $installdir/usr/share/doc/cuda
    mv doc/pdf $installdir/usr/share/doc/cuda
    mv doc/EULA.txt $installdir/usr/share/doc/cuda
    rm -rfv EULA.txt
    install -dm00755 $installdir/usr/share/man/man{1,7}
    install -Dm00644 -t $installdir/usr/share/man/man1 doc/man/man1/*
    install -Dm00644 -t $installdir/usr/share/man/man7 doc/man/man7/*
    rm -rfv doc

    unlink include
    unlink lib64
    mv targets/x86_64-linux/include include
    mv targets/x86_64-linux/lib lib64
    rm -rfv targets

    # Header files
    find $installdir/%libdir%/cuda/include -type f -print0 | xargs -0 chmod 644
    install -dm00755 $installdir/usr/include/cuda
    install -Dm00644 $workdir/cublas/include/cublas_version.h include/
    for f in $installdir/%libdir%/cuda/include/*; do
        ln -sf %libdir%/cuda/include/`basename $f` $installdir/usr/include/cuda
    done

    # Libraries
    # Remove OpenCL
    rm -v $installdir/%libdir%/cuda/lib64/libOpenCL.so*
    # We don't use the libraries in `stubs` subdir
    rm -rfv $installdir/%libdir%/cuda/lib64/stubs
    for f in lib64/lib*.so* lib64/lib*.a; do
        ln -sf %libdir%/cuda/lib64/`basename $f` $installdir/%libdir%
    done

    # This is for tensorflow 1.12
    short_version=`echo %version% | cut -f1,2 -d.`
    for f in $installdir/%libdir%/cuda/lib64/lib*.so; do
        if [[ ! -e $installdir/%libdir%/cuda/lib64/$(basename $f).${short_version} ]]; then
            ln -sf $(basename $f) $installdir/%libdir%/cuda/lib64/$(basename $f).${short_version}
        fi
    done

    # nvvm
    ln -sf %libdir%/cuda/nvvm/bin/cicc $installdir/usr/bin
    ln -sf %libdir%/cuda/nvvm/include/nvvm.h $installdir/usr/include/cuda
    for f in nvvm/lib64/lib*.so*; do
        ln -sf %libdir%/cuda/nvvm/lib64/`basename $f` $installdir/%libdir%
    done

    # pkgconfig
    install -dm00755 $installdir/usr/lib64/pkgconfig
    install -Dm00644 -t $installdir/usr/lib64/pkgconfig $pkgfiles/*.pc

    # samples
    mv $workdir/cuda-samples samples
    find $installdir/%libdir%/cuda/samples -type f -name "*install*" -delete
    find $installdir/%libdir%/cuda/samples -type f -name "findgllib.mk" -print0 | 
        xargs -0 sed -i '57i\    GLPATH    ?= /usr/lib64/nvidia\n    GLLINK    ?= -L/usr/lib64/nvidia\n    DFLT_PATH ?= /usr/lib64'
    find $installdir/%libdir%/cuda/samples -type f -name "Makefile" -print0 | 
        xargs -0 sed -i -e 's/usr\/local\/cuda/usr\/lib64\/cuda/g'

    # extras/{CUPTI,Debugger}
    for dir in CUPTI Debugger; do
        install -dm00755 $installdir/usr/include/cuda/$dir
        for f in $installdir/%libdir%/cuda/extras/$dir/include/*; do
            ln -sf %libdir%/cuda/extras/$dir/include/`basename $f` $installdir/usr/include/cuda/$dir
        done
        for f in $installdir/%libdir%/cuda/extras/$dir/lib64/*; do
            ln -sf %libdir%/cuda/extras/$dir/lib64/`basename $f` $installdir/%libdir%
        done
    done

    install -dm00755 $installdir/usr/include/cuda/Sanitizer
    for f in $installdir/%libdir%/cuda/extras/Sanitizer/include/*; do
        ln -sf %libdir%/cuda/extras/Sanitizer/include/`basename $f` $installdir/usr/include/cuda/Sanitizer
    done
    ln -sf %libdir%/cuda/extras/Sanitizer/libsanitizer-public.so $installdir/%libdir%

    popd

    # Clean up
    find $installdir/%libdir%/cuda -name "*.bat" -delete
    # Clean empty directories
    find $installdir/%libdir%/cuda -type d -empty -delete
