name       : cuda
version    : 10.1.168
release    : 6
source     :
    - https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.168_418.67_linux.run : 4fcad1d2af35495ff57b8ea5851f6031c3d350d14e88f5db12c40a4074ddf43f
extract    : no
license    : EULA
component  : programming.library
summary    : NVIDIA's GPU programming toolkit
description: |
    CUDA® is a parallel computing platform and programming model developed by NVIDIA for general computing on graphical processing units (GPUs).
strip      : no
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freeglut)
    - pkgconfig(glu)
    - pkgconfig(libpulse)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xrandr)
rundeps    :
    - openjdk-8
build      : |
    CUDA_INSTALL_FILE=$(basename $sources/cuda_${version}_*_linux*)
    sh $sources/$CUDA_INSTALL_FILE --extract=$workdir
    #./cuda-linux.${version}-*.run -noprompt -nosymlink -no-man-page -prefix=$PKG_BUILD_DIR/cuda_build
    #./cuda-samples.${version}-*.run -noprompt -prefix=$PKG_BUILD_DIR/cuda_build/samples -cudaprefix=%libdir%/cuda
install    : |
    install -dm00755 $installdir/%libdir% $installdir/usr/bin
    mv $workdir/cuda-toolkit $installdir/%libdir%/cuda

    pushd $installdir/%libdir%/cuda

    # Adjust path for NSight plugin
    sed -i -e 's|`dirname $0`/..|%libdir%/cuda|g' bin/nsight_ee_plugins_manage.sh

    # Java stuff
    # jre
    rm -rfv jre
    sed -i -e '/^-vm/d' -e '/jre\/bin\/java/d' libnsight/nsight.ini libnvvp/nvvp.ini
    #sed -i -e 's|../jre/bin/java|/usr/bin/java|g' libnsight/nsight.ini libnvvp/nvvp.ini

    install -dm00755 $installdir/usr/share/pixmaps
    install -Dm00644 libnsight/icon.xpm $installdir/usr/share/pixmaps/nsight.xpm
    install -Dm00644 libnvvp/icon.xpm $installdir/usr/share/pixmaps/nvvp.xpm
    #mv libnsight $installdir/%libdir%/nsight
    #mv libnvvp $installdir/%libdir%/nvvp
    #mv nsightee_plugins $installdir/%libdir%/nsight/
    rm -v $installdir/%libdir%/cuda/bin/nsight
    rm -v $installdir/%libdir%/cuda/bin/nvvp
    ln -sv %libdir%/cuda/libnsight/nsight $installdir/usr/bin
    ln -sv %libdir%/cuda/libnvvp/nvvp $installdir/usr/bin
    install -dm00755 $installdir/usr/share/applications
    install -Dm00644 $pkgfiles/nsight.desktop $installdir/usr/share/applications/nsight.desktop
    install -Dm00644 $pkgfiles/nvvp.desktop $installdir/usr/share/applications/nvvp.desktop

    # Binaries
    find $installdir/%libdir%/cuda/bin -type f -name "*install*" -delete
    rm -v $installdir/%libdir%/cuda/bin/nvcc.profile
    install -Dm00644 $pkgfiles/nvcc.profile $installdir/%libdir%/cuda/bin/nvcc.profile

    # Docs
    install -dm00755 $installdir/usr/share/doc/cuda
    mv doc/html $installdir/usr/share/doc/cuda
    mv doc/pdf $installdir/usr/share/doc/cuda
    mv doc/EULA.txt $installdir/usr/share/doc/cuda
    rm -rfv EULA.txt
    install -dm00755 $installdir/usr/share/man/man{1,7}
    install -Dm00644 -t $installdir/usr/share/man/man1 doc/man/man1/*
    install -Dm00644 -t $installdir/usr/share/man/man7 doc/man/man7/*
    rm -rfv doc

    unlink include
    unlink lib64
    mv targets/x86_64-linux/include include
    mv targets/x86_64-linux/lib lib64
    rm -rfv targets

    # Header files
    find $installdir/%libdir%/cuda/include -type f -print0 | xargs -0 chmod 644

    # Libraries
    # Remove OpenCL
    rm -v $installdir/%libdir%/cuda/lib64/libOpenCL.so*
    # We don't use the libraries in `stubs` subdir
    rm -rfv $installdir/%libdir%/cuda/lib64/stubs

    # nvvm
    ln -sv %libdir%/cuda/nvvm/bin/cicc $installdir/usr/bin

    # samples
    mv $workdir/cuda-samples samples
    find $installdir/%libdir%/cuda/samples -type f -name "*install*" -delete
    find $installdir/%libdir%/cuda/samples -type f -name "findgllib.mk" -print0 | 
        xargs -0 sed -i '57i\    GLPATH    ?= /usr/lib64/nvidia\n    GLLINK    ?= -L/usr/lib64/nvidia\n    DFLT_PATH ?= /usr/lib64'
    find $installdir/%libdir%/cuda/samples -type f -name "Makefile" -print0 | 
        xargs -0 sed -i -e 's/usr\/local\/cuda/usr\/lib64\/cuda/g'

    popd

    install -Dm00644 $pkgfiles/cuda.conf $installdir/usr/share/ld.so.conf.d/cuda.conf
    install -Dm00644 $pkgfiles/70-cuda.sh $installdir/usr/share/defaults/etc/profile.d/70-cuda.sh

    # Clean up
    find $installdir/%libdir%/cuda -name "*.bat" -delete
    # Clean empty directories
    find $installdir/%libdir%/cuda -type d -empty -delete
