name       : python-torchvision
version    : 0.2.1
release    : 2
source     :
    - https://github.com/pytorch/vision/archive/v0.2.1.tar.gz : 91f1e21121dca7e14ec35b5f2127da77c8c52e61d39957ab5dd4a719a837a04c
license    : BSD-3-Clause
component  : programming.python
summary    : Datasets, Transforms and Models specific to Computer Vision
description: |
    The torchvision package consists of popular datasets, model architectures, and common image transformations for computer vision.
rundeps    :
    - numpy
    - python-pillow
    - python-pytorch
    - python-six
    - python-tqdm
build      : |
    %python3_setup
install    : |
    %python3_install
