name       : python-keras-applications
version    : 1.0.6
release    : 2
source     :
    - https://files.pythonhosted.org/packages/0c/f1/8d3dc4b770d51f0591c2913e55dd69e70c2e217835970ffa0b1acc091d8e/Keras_Applications-1.0.6.tar.gz : a03af60ddc9c5afdae4d5c9a8dd4ca857550e0b793733a5072e0725829b87017
license    : MIT
component  : programming.python
summary    : Reference implementations of popular deep learning models
description: |
    Keras Applications is the applications module of the Keras deep learning library. It provides model definitions and pre-trained weights for a number of popular archictures, such as VGG16, ResNet50, Xception, MobileNet, and more. Read the documentation at: https://keras.io/applications/
rundeps    :
    - numpy
    - python-h5py
build      : |
    %python3_setup
install    : |
    %python3_install
