name       : pycuda
version    : 2018.1.1
release    : 2
source     :
    - https://files.pythonhosted.org/packages/58/33/cced4891eddd1a3ac561ff99081019fddc7838a07cace272c941e3c2f915/pycuda-2018.1.1.tar.gz : 49d575fca3fd3c95467c3b0fb51967ad17d0c4cc18e078a6748309af4de36a8d
      #- git|https://github.com/inducer/pycuda : v2018.1.1
license    :
    - MIT
    - Apache-2.0
component  : programming.python
summary    : CUDA integration for Python, plus shiny features
description: |
    PyCUDA lets you access Nvidia's CUDA parallel computation API from Python.
builddeps  :
    - pkgconfig(cuda)
    - pkgconfig(python3)
    - libboost-devel
    - numpy
    - nvidia-glx-driver-common
rundeps    :
    - mako
    - python-pytools
setup      : |
    python3 configure.py --cuda-root=%libdir%/cuda \
                         --no-use-shipped-boost \
                         --boost-python-libname=boost_python3
build      : |
    %python3_setup
install    : |
    %python3_install
