name       : network-manager-l2tp
version    : 1.2.10
release    : 2
source     :
    - https://github.com/nm-l2tp/network-manager-l2tp/archive/1.2.10.tar.gz : 6835bbf615d8a028505167d51cd6a082dacee7474c35bd370b918a56e261efdb
license    : GPL-2.0-or-later
component  : network.base
summary    : L2TP and L2TP/IPsec support for NetworkManager
description: |
    L2TP and L2TP/IPsec support for NetworkManager 
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-1)
    - ppp-devel
rundeps    :
    - libreswan
    - xl2tpd
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
