name       : python-dm-sonnet
version    : 1.27
release    : 2
source     :
    - https://github.com/deepmind/sonnet/archive/v1.27.tar.gz : b3ea44d75e2466bb016a17023b3afa2e50c9de91f5357d1b299ced51f848f4aa
license    : Apache-2.0
component  : programming.python
summary    : Tensorflow-based neural network library
description: |
    Sonnet is a library built on top of TensorFlow for building complex neural networks.
networking : yes
builddeps  :
    - bazel
    - python-wheel
rundeps    :
    - python-absl-py
    - python-contextlib2
    - python-semanticversion
    - python-tensorflow-probability
    - python-wrapt
build      : |
    bazel build :install
    bazel shutdown
    mkdir -p $PKG_BUILD_DIR/build_sonnet
    ./bazel-bin/install $PKG_BUILD_DIR/build_sonnet python3
install    : |
    pip3 install --no-deps --root=$installdir $PKG_BUILD_DIR/build_sonnet/*.whl
