name       : python-dm-sonnet
version    : 1.34
release    : 1
source     :
    - https://github.com/deepmind/sonnet/archive/v1.34.tar.gz : 71b018001ced180ba525d9252c78025de359e7f3b7defd37aa0368255c2b0ab4
license    : Apache-2.0
component  : programming.python
summary    : Tensorflow-based neural network library
description: |
    Sonnet is a library built on top of TensorFlow for building complex neural networks.
networking : yes
builddeps  :
    - bazel
    - git
    - python-wheel
rundeps    :
    - python-absl-py
    - python-contextlib2
    - python-semanticversion
    - python-tensorflow-probability
    - python-wrapt
build      : |
    bazel build :install
    bazel shutdown
    mkdir -p $PKG_BUILD_DIR/build_sonnet
    ./bazel-bin/install $PKG_BUILD_DIR/build_sonnet python3
install    : |
    pip3 install --no-deps --root=$installdir $PKG_BUILD_DIR/build_sonnet/*.whl
