name       : python-pkgconfig
version    : 1.4.0
release    : 2
source     :
    - https://github.com/matze/pkgconfig/archive/v1.4.0.tar.gz : 38c5de8392f4acfe7f36b25d113c496d68f534e983afdbd0ba7240c8c475b161
license    : MIT
component  : programming.python
summary    : A Python interface to the pkg-config command line tool
description: |
    A Python interface to the pkg-config command line tool
build      : |
    %python3_setup
install    : |
    %python3_install
