name       : python-keras-preprocessing
version    : 1.0.5
release    : 2
source     :
    - https://files.pythonhosted.org/packages/34/ef/808258b8b5e39ae4d7c5606d03d3bbaf68bb8a639ce2e64220ea4ca12ff9/Keras_Preprocessing-1.0.5.tar.gz : ef2e482c4336fcf7180244d06f4374939099daa3183816e82aee7755af35b754
license    : MIT
component  : programming.python
summary    : Utilities for working with image data, text data, and sequence data
description: |
    Keras Preprocessing is the data preprocessing and data augmentation module of the Keras deep learning library. It provides utilities for working with image data, text data, and sequence data. Read the documentation at: https://keras.io
rundeps    :
    - python-six
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
